
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Irish_Grover } from "next/font/google";
import Head from "next/head";

const irishGrover = Irish_Grover({
  weight:"400",
  variable:"--font-IrishGrover",
  subsets:['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <Head>
      {/* <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" /> */}
<link href="https://fonts.googleapis.com/css2?family=Irish+Grover&display=swap" rel="stylesheet"/>
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css2?family=Irish+Grover&display=swap" rel="stylesheet"/>   
     
      </Head>
      <body className={irishGrover.variable}>        
        {children}
        </body>
    </html>
  );
}
